baseURL = "http://storyweb.info/"
languageCode = "en-uk"
title = "Story:Web"
theme = "introduction"
publishDir = "docs"
sectionPagesMenu = "main"

[params]
    themeStyle                   = "auto"                  # Choose "light" or "dark" or "auto"
    fadeIn                       = true                    # Turn on/off the fade-in effect
    fadeInIndex                  = false                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "Jan 2, 2006"
    email                        = "simon.bowen@newcastle.ac.uk"   # E-mail address for contact section
    # customCSS                  = ["custom.css"]           # Include custom css files placed under assets/
    # customJS                   = ["foo.js"]              # Include custom JavaScript files placed under assets/
    # plausible                  = true                    # Use Plausible analytics (requires an account at Plausible.io)

    # Configure the home page
    [params.home]
        introHeight              = "medium"            # Input either "medium" or "large" or "fullheight"
        showLatest               = true                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        allPostsArchiveFormat    = true                    # show all posts in an archive format
        numberOfProjectsToShow   = 3                       # Maximum number of projects to show on home page. Unset or comment out to show all projects
        localTime                = true                    # Show your current local time in contact section
        timeZone                 = "GB"   # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat               = "en-US"                 # Language specific format to use
    [params.projects]
        useTwoColumns            = false                   # Use a layout with two columns instead of three

[markup.goldmark.renderer]
unsafe= true

[menu]

  [[menu.main]]
    identifier = "home"
    name = "home"
    title = "home"
    url = "/"
    weight = -110

 [[menu.main]]
    identifier = "storyweb"
    name = "The Story:Web so far"
    title = "The Story:Web so far"
    url = "/storyweb/"
    weight = -100